name: Build and Release
on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: pyinstaller --onedir --name "GPT2_Offline" --collect-all transformers --collect-all accelerate main.py

    - name: Archive Release
      shell: powershell
      run: Compress-Archive -Path dist/GPT2_Offline/* -DestinationPath GPT2_Offline_v5.2.zip

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: GPT2_Offline_v5.2.zip
        name: Stable Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        body: "Автоматическая сборка оффлайн-нейросети GPT-2."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
